### ISSUE TITLE
Update copyright statements

### ISSUE THREAD

**Issue by suever** [fornwaltlab/framewise_strain_plugin#1]
So do we want to use "Fornwalt Lab" or "Cardiac Imaging Technology Lab" for the copyright lines?

**Comment by chaggerty** [comment]
My preference would probably be "Cardiac Imaging Technology Lab". 

The only two places I'm seeing copyright is the license file and the header on the m file itself.. am I missing anything?

**Comment by suever** [comment]
Yup those are the two main ones. I was going to update the other plugins and just wanted to make sure we were consistent.
